sudo: required
services:
  - docker

before_install:
  - docker build -t docker-id/nestjs-mongoose-template-test -f ./Dockerfile.dev .

script:
  - docker run -e CI=true -e NODE_ENV=test -e PORT=3000 -e JWT_SECRET=U68kT5rUQuVEKqDMqzbd docker-id/nestjs-mongoose-template-test npm run test
  - docker run -e CI=true -e NODE_ENV=test -e PORT=3000 -e JWT_SECRET=U68kT5rUQuVEKqDMqzbd docker-id/nestjs-mongoose-template-test npm run test:e2e

after_success:
  - docker build -t docker-id/nestjs-mongoose-template .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push docker-id/nestjs-mongoose-template

deploy:
  provider: elasticbeanstalk
  region: 'aws-region'
  app: 'nestjs-mongoose-template'
  env: 'nestjs-mongoose-template-env'
  bucket_name: 'aws-s3-bucket-name'
  bucket_path: 'nestjs-mongoose-template'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
